# Generated by Django 2.0.3 on 2018-03-16 19:42

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contents_html',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='path',
            field=models.CharField(max_length=127, validators=[django.core.validators.MinLengthValidator(6), django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
