# Generated by Django 2.0.3 on 2018-03-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contents_html',
            field=models.TextField(default='', editable=False),
        ),
    ]
