# Generated by Django 2.1.3 on 2018-11-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_blocker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestBlocker',
        ),
    ]
