# Generated by Django 2.0.3 on 2018-04-23 17:00

import annoying.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import json
import queueapp.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Buffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('cmp_function', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, max_length=30, unique=True)),
                ('props', annoying.fields.JSONField(default=queueapp.utils.new_dict, deserializer=json.loads, editable=False, serializer=annoying.fields.dumps)),
                ('is_running', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('buffer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='queueapp.Buffer')),
            ],
        ),
        migrations.CreateModel(
            name='JenkinsActuator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=False)),
                ('project_name', models.CharField(max_length=60)),
                ('from_buffer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='queueapp.Buffer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JiraPoller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=False)),
                ('interval', models.DurationField(default=datetime.timedelta(0, 60))),
                ('updated', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('query', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='log',
            name='queue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='queueapp.Queue'),
        ),
        migrations.AddField(
            model_name='jirapoller',
            name='queue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='queueapp.Queue'),
        ),
        migrations.AddField(
            model_name='jirapoller',
            name='to_buffer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='queueapp.Buffer'),
        ),
        migrations.AddField(
            model_name='jenkinsactuator',
            name='queue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='queueapp.Queue'),
        ),
        migrations.AddField(
            model_name='buffer',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='queueapp.Queue'),
        ),
        migrations.AddField(
            model_name='autofilter',
            name='from_buffer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='to_filter', to='queueapp.Buffer'),
        ),
        migrations.AddField(
            model_name='autofilter',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='queueapp.Queue'),
        ),
        migrations.AddField(
            model_name='autofilter',
            name='to_buffer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='from_filter', to='queueapp.Buffer'),
        ),
    ]
