# Generated by Django 2.0.3 on 2018-05-07 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queueapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NopFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=False)),
                ('from_buffer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='to_nopfilter', to='queueapp.Buffer')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='queueapp.Queue')),
                ('to_buffer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='from_nopfilter', to='queueapp.Buffer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='log',
            name='count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autofilter',
            name='from_buffer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='to_autofilter', to='queueapp.Buffer'),
        ),
        migrations.AlterField(
            model_name='autofilter',
            name='to_buffer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='from_autofilter', to='queueapp.Buffer'),
        ),
    ]
