# Generated by Django 2.1 on 2019-02-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueapp', '0006_cmp_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='buffer',
            name='intended_status',
            field=models.CharField(default='Integrating', max_length=20),
        ),
        migrations.AlterField(
            model_name='buffer',
            name='cmp_rules',
            field=models.TextField(blank=True, help_text='Move these issues to the top of the buffer. Shell-style patterns, one per line'),
        ),
    ]
