# Generated by Django 2.0b1 on 2017-10-31 17:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_name', models.CharField(max_length=20)),
                ('mount_point', models.CharField(max_length=40)),
                ('is_healthy', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpath', models.CharField(max_length=1000)),
                ('size', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('storage_class', models.PositiveSmallIntegerField(default=1)),
                ('gen', models.PositiveSmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000)),
                ('is_healthy', models.BooleanField()),
                ('last_checked', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('disk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diskarray.Disk')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copies', to='diskarray.File')),
            ],
            options={
                'verbose_name_plural': 'file copies',
            },
        ),
        migrations.CreateModel(
            name='Oplog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=1000)),
                ('stage', models.CharField(choices=[('waiting', 'waiting'), ('working', 'working'), ('ended', 'ended')], default='waiting', max_length=10)),
                ('error_code', models.SmallIntegerField(default=-1)),
                ('stdout', models.TextField()),
                ('stderr', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='filecopy',
            unique_together={('disk', 'file')},
        ),
    ]
