# Generated by Django 2.0.3 on 2018-05-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueapp', '0002_related_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='number_tries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issue',
            name='verdict',
            field=models.CharField(choices=[('pending', 'pending'), ('succeeded', 'succeeded'), ('failed', 'failed')], default='pending', max_length=10),
        ),
    ]
