# Generated by Django 2.0.3 on 2018-06-17 14:50

import annoying.fields
from django.db import migrations, models
import json
import queueapp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('queueapp', '0003_verdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='buffer',
            name='cmp_rules',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='jenkinsactuator',
            name='issue_param',
            field=models.CharField(default='ISSUE', max_length=30),
        ),
        migrations.AddField(
            model_name='jenkinsactuator',
            name='issue_param2',
            field=models.CharField(default='ISSUES', max_length=30),
        ),
        migrations.AddField(
            model_name='jenkinsactuator',
            name='project_name2',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='issue',
            name='props',
            field=annoying.fields.JSONField(default=queueapp.utils.new_dict, deserializer=json.loads, serializer=annoying.fields.dumps),
        ),
    ]
