# Generated by Django 2.0.3 on 2018-07-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueapp', '0004_jenkins_project2'),
    ]

    operations = [
        migrations.AddField(
            model_name='autofilter',
            name='issues_per_cycle',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='jenkinsactuator',
            name='multiple_count_lower',
            field=models.PositiveSmallIntegerField(default=3, help_text='Inclusive'),
        ),
        migrations.AddField(
            model_name='jenkinsactuator',
            name='multiple_count_upper',
            field=models.PositiveSmallIntegerField(default=5, help_text='Inclusive'),
        ),
        migrations.AlterField(
            model_name='jenkinsactuator',
            name='project_name2',
            field=models.CharField(blank=True, help_text='Many issues at once (optional)', max_length=60),
        ),
    ]
